Repository wp-media/wp-rocket-cli, pull requests merged in 2021-01, with the labels that each got.

#37 Remove deprecation and update the code.
  command.php
  composer.json
Labels: type: enhancement

#39 Closes #21 - Enable / Disable CDN with the specified host and zone.
  README.md
  command.php
Labels: type: new feature

#40 Closes #25 Clean command needs to clean minify folder
  command.php
Labels: type: enhancement

#41 Fix #22 Activate/Deactivate does not trigger htaccess regeneration
  README.md
  command.php
Labels: type: bug
